version: "3.4"

services:
  postgres:
    image: postgres:10.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: dsd
      POSTGRES_PASSWORD: dsdLozinkaMuySegura
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/

  angular:
    build: './frontend/'
    image: angular:1.0
    ports:
      - '4200:4200'
    volumes:
      - ./frontend/:/home/node/app/
    links:
      - django
    command: sh docker_dev.sh

  django:
    build: './backend/'
    image: django:1.0
    ports:
      - '8000:8000'
    volumes:
      - ./backend/:/app/
    links:
      - postgres
    command: sh docker_dev.sh
